# Makefile para ProyectoArqui

all: ProyectoArqui

ProyectoArqui: ProyectoArqui.o
	g++ -o ProyectoArqui ProyectoArqui.o

ProyectoArqui.o: ProyectoArqui.cpp
	g++ -c ProyectoArqui.cpp -o ProyectoArqui.o

clean:
	rm -f *.o ProyectoArqui